"""endorsement table created

Revision ID: 025b4d2a3eb4
Revises: 
Create Date: 2025-06-24 08:26:35.148071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025b4d2a3eb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_endorsement_t1',
    sa.Column('t_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('t_refno', sa.String(), nullable=False),
    sa.Column('t_date_endorsed', sa.Date(), nullable=False),
    sa.Column('t_category', sa.Enum('MB', 'DC', name='categoryenum'), nullable=False),
    sa.Column('t_prodcode', sa.String(), nullable=False),
    sa.Column('t_lotnumberwhole', sa.String(), nullable=False),
    sa.Column('t_qtykg', sa.Float(), nullable=False),
    sa.Column('t_wtlot', sa.Float(), nullable=False),
    sa.Column('t_status', sa.Enum('PASSED', 'FAILED', name='statusenum'), nullable=False),
    sa.Column('t_endorsed_by', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('t_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_endorsement_t1')
    # ### end Alembic commands ###
