"""added t_bag_num in the endorsement table 2 and remove the t_bag_num in endorsement table 1

Revision ID: 0620f898789f
Revises: 335fdc5e5a56
Create Date: 2025-07-21 15:49:04.794727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0620f898789f'
down_revision: Union[str, Sequence[str], None] = '335fdc5e5a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_endorsement_t1', 't_bag_num')
    op.add_column('tbl_endorsement_t2', sa.Column('t_bag_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_endorsement_t2', 't_bag_num')
    op.add_column('tbl_endorsement_t1', sa.Column('t_bag_num', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
