"""added new column for endorsement table 2 'is_lot_number_entered' with nullable false

Revision ID: 335fdc5e5a56
Revises: eb6c989ddc39
Create Date: 2025-07-21 14:29:18.694589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335fdc5e5a56'
down_revision: Union[str, Sequence[str], None] = 'eb6c989ddc39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_endorsement_t2', 'is_lot_number_entered',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='Indicates if the lot number has already been inputted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_endorsement_t2', 'is_lot_number_entered',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='Indicates if the lot number has already been inputted')
    # ### end Alembic commands ###
