"""modify refno and lotnumbersingle

Revision ID: 4417d1359e38
Revises: fd1368be971d
Create Date: 2025-07-01 09:41:29.652810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4417d1359e38'
down_revision: Union[str, Sequence[str], None] = 'fd1368be971d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tbl_endorsement_t2_t_refno_key'), 'tbl_endorsement_t2', type_='unique')
    op.create_unique_constraint('uq_refno_lot', 'tbl_endorsement_t2', ['t_refno', 't_lotnumbersingle'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_refno_lot', 'tbl_endorsement_t2', type_='unique')
    op.create_unique_constraint(op.f('tbl_endorsement_t2_t_refno_key'), 'tbl_endorsement_t2', ['t_refno'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
