"""added is_deleted column in the endorsement table2

Revision ID: 4bc3b13d74a1
Revises: 4417d1359e38
Create Date: 2025-07-01 09:48:20.609283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc3b13d74a1'
down_revision: Union[str, Sequence[str], None] = '4417d1359e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_endorsement_t2', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_endorsement_t2', 'is_deleted')
    # ### end Alembic commands ###
