"""added a t_bag_num column in the database

Revision ID: 4c0136e70383
Revises: 309fa2d722c0
Create Date: 2025-07-12 14:04:40.282061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0136e70383'
down_revision: Union[str, Sequence[str], None] = '309fa2d722c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_endorsement_t1', sa.Column('t_bag_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_endorsement_t1', 't_bag_num')
    # ### end Alembic commands ###
