"""Initial migration

Revision ID: 75d63edcb13a
Revises: 
Create Date: 2025-06-23 15:25:19.487900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75d63edcb13a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_endorsement_t1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_endorsement_t1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('t_refno', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('t_date_endorsed', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('t_category', postgresql.ENUM('MB', 'DC', name='categoryenum'), autoincrement=False, nullable=False),
    sa.Column('t_prodcode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('t_lotnumberwhole', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('t_qtykg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('t_wtlot', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('t_status', postgresql.ENUM('PASSED', 'FAILED', name='statusenum'), autoincrement=False, nullable=False),
    sa.Column('t_endorsed_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_endorsement_t1_pkey'))
    )
    # ### end Alembic commands ###
