"""added user and authlog tables

Revision ID: 80f035759479
Revises: 025b4d2a3eb4
Create Date: 2025-06-24 14:45:38.496179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f035759479'
down_revision: Union[str, Sequence[str], None] = '025b4d2a3eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('workstation_name', sa.String(length=40), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'SUPERVISOR', 'USER', 'DISABLED', name='userrole'), nullable=False),
    sa.Column('department', sa.Enum('LAB', 'PRODUCTION', 'WAREHOUSE', name='department'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('auth_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('additional_info', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
