"""added unique property to endorsement_table_1 column lotnumberwhole

Revision ID: d42eb08ed17e
Revises: 4c0136e70383
Create Date: 2025-07-14 09:46:09.010898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42eb08ed17e'
down_revision: Union[str, Sequence[str], None] = '4c0136e70383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tbl_endorsement_t1', ['t_lotnumberwhole'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_endorsement_t1', type_='unique')
    # ### end Alembic commands ###
