"""enum fields turned into uppercase

Revision ID: d4cd3a44128d
Revises: f4fbc1cf60fd
Create Date: 2025-06-24 16:47:22.711788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4cd3a44128d'
down_revision: Union[str, Sequence[str], None] = 'f4fbc1cf60fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
