"""added new column for endorsement table 2 'is_lot_number_entered'

Revision ID: eb6c989ddc39
Revises: d42eb08ed17e
Create Date: 2025-07-21 14:25:57.268806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6c989ddc39'
down_revision: Union[str, Sequence[str], None] = 'd42eb08ed17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_endorsement_t2', sa.Column('is_lot_number_entered', sa.Boolean(), nullable=True, comment='Indicates if the lot number has already been inputted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_endorsement_t2', 'is_lot_number_entered')
    # ### end Alembic commands ###
