"""Initial migration with endorsement tables

Revision ID: ede5364dc4a1
Revises: f8e9787f8402
Create Date: 2025-06-23 16:33:54.007086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede5364dc4a1'
down_revision: Union[str, Sequence[str], None] = 'f8e9787f8402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_endorsement_t1', sa.Column('t_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('tbl_endorsement_t1', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_endorsement_t1', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('tbl_endorsement_t1', 't_id')
    # ### end Alembic commands ###
