"""added IT department section

Revision ID: f08e3280457a
Revises: d4cd3a44128d
Create Date: 2025-06-24 16:57:18.968422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08e3280457a'
down_revision: Union[str, Sequence[str], None] = 'd4cd3a44128d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE department ADD VALUE IF NOT EXISTS 'IT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
