"""adjusted reference of reverse lookup item

Revision ID: fd1368be971d
Revises: f08e3280457a
Create Date: 2025-06-28 11:27:48.798555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1368be971d'
down_revision: Union[str, Sequence[str], None] = 'f08e3280457a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # create first the table endorsement that have a unique constraint
    op.create_unique_constraint(None, 'tbl_endorsement_t1', ['t_refno'])

    op.create_table('tbl_endorsement_t2',
    sa.Column('t_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('t_refno', sa.String(), nullable=False, unique=True),
    sa.Column('t_lotnumbersingle', sa.String(length=10), nullable=False),
    sa.Column('t_qty', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['t_refno'], ['tbl_endorsement_t1.t_refno'], ),
    sa.PrimaryKeyConstraint('t_id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_endorsement_t1', type_='unique')
    op.drop_table('tbl_endorsement_t2')
    # ### end Alembic commands ###
